run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  exclude-use-default: false
  exclude-dirs:
    - tmp
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019"
